### ISSUE TITLE
File Ultima.Underworld.Portable.zip is tagged as having a "Trojan.GenericKD.67343013" virus

### ISSUE THREAD

**Issue by bliznik** [vini1264/Ultima-Underworld-Portable#1]
I'm able to download and execute the "source code" just fine, but when I try to download the zip file, I get a notification of that virus.

You might want to submit the file to a place like here: https://www.bitdefender.com/consumer/support/answer/29358/ in order to ensure that it can be downloaded. Otherwise, it will be deleted by every antivirus program and even web browsers.

**Comment by vini1264** [comment]
Thanks for reporting, I'll update the zip from releases to use just the .bat files instead of those exes, as they flag anti-viruses with a false positive

**Comment by Noomene** [comment]
Got similar virus warning. Not sure this is just an "exes" issue though. Both Kaspersky and Avira reported viruses in the zip. Not so nice of you buddy.

**Comment by vini1264** [comment]
> Got similar virus warning. Not sure this is just an "exes" issue though. Both Kaspersky and Avira reported viruses in the zip. Not so nice of you buddy.

Fixed, there wasn't any virus or anything, just a false positive. check version 1.1 here:

https://github.com/vini1264/Ultima-Underworld-Portable/releases/tag/v1.1
